### ISSUE TITLE
Change `setup_anndata` to not use `adata.obs` and use a "private" `.obsm` field.

### ISSUE THREAD

**Issue by Munfred** [YosefLab/scvi-tools#1044]
When I save a trained model the following columns get added to `adata.obs`:`_scvi_batch`,`_scvi_labels`,`_scvi_local_l_mean`,`_scvi_local_l_var`.

It would make sense to save them in another place such as `adata.obsm['__scvi__'] so indicate to the user these are internal variables that should not be touched, and to tuck them in a place where they are less visible and less likely to get mucked with accidentally.

The main drawback of doing this is breaking compatibility with loading previous models, but perhaps something worthwhile to keep in the list for a 1.0 release?

**Comment by adamgayoso** [comment]
It's a good idea, we can further discuss

**Comment by adamgayoso** [comment]
@jjhong922 lmk if you have any thoughts about this

**Comment by jjhong922** [comment]
I'm not sure I see the major benefit of moving these around since we will have additional added .obsm fields added regardless (extra covariates). i.e. one obsm would not suffice to be a central store for all scvi-tools specific data. I'm hoping that we will be able to get of the integer conversions from the AnnData and reduce the number of columns added, but this is something we are still exploring.

**Comment by adamgayoso** [comment]
@jjhong922 sounds like we won't pursue this, should we close this issue?

**Comment by jjhong922** [comment]
Yes don't think we have plans to do this given we aim to have a more modular approach.
