### ISSUE TITLE
p-values associated with DE genes

### ISSUE THREAD

**Issue by HaniJieunKim** [YosefLab/scvi-tools#1047]
Hi authors of SCVI,

Thanks for the fantastic tool. 

I am running DE analysis using SCVI. I was wondering whether you provide p-values associated with the DE genes? 

There appears to be a binary label called `is_de_fdr_0.05` among the outputs, but I cannot seem to find the p-values. 

Thank you!

Best regards,

Hani

**Comment by PierreBoyeau** [comment]
Hi Hani,
You won't be able to obtain exact p-values from scVI's DE module because it does not rely on frequentist hypothesis testing techniques. In particular, we are not constructing DE genes from p-values.
Both `vanilla` and `change` modes rely on the same logic, but for simplicity let me describe `change`. First, we rank genes by their posterior DE probability.
Then, to determine how many genes to tag as DE, we compute posterior expectations of the False Discovery Rate and ensure that it is below an-user specified value alpha (in the example you described 0.05).
I hope this clarified why you won't be able to get p-values.
I am closing this, but feel free to reach the [forum](https://discourse.scvi-tools.org/) if you have other questions.

**Comment by HaniJieunKim** [comment]
Great! Thanks for the quick response.
