### ISSUE TITLE
Reproducibility of SCVI.load on different architectures

### ISSUE THREAD

**Issue by grst** [YosefLab/scvi-tools#1048]
I trained an scVI model on a machine with an AMD EPYC 7352 CPU and a Quadro RTX 8000 GPU and saved the model with `model.save()`. When I load the model on the same machine and retrieve the latent representation, the resulting UMAP is different to when I load the model on a different machine with a Intel(R) Xeon(R) CPU E7-4850 v4 CPU and no GPU. 

Is that expected? I was hoping to share the trained model alongside my code to make the analysis reproducible. If so, what's the recommended way to share reproducible analyses with scVI? (I am aware that *training* the model is not expected to be reproducible). 

Here's the code I use to retrieve the latent representation and compute the UMAP: 

```python
model = scvi.model.SCVI.load(f"{output_dir}/scvi_model_all_genes", adata_scvi)
adata.obsm["X_scVI"] = model.get_latent_representation(adata_scvi)
sc.pp.neighbors(adata, use_rep="X_scVI", n_neighbors=15)
sc.tl.umap(adata)
```

#### Versions:

> 0.8.1

#### Model loaded on the AMD machine: 
<img src="https://user-images.githubusercontent.com/7051479/116978552-250b5800-acc4-11eb-86e1-acbce39f41b5.png" width="400">

#### Model loaded on the Intel machine: 
<img src="https://user-images.githubusercontent.com/7051479/116978568-2c326600-acc4-11eb-9340-1c266b62b630.png" width="400">

(Neighbors and UMAP were computed on the intel machine in both cases to make sure the instability is not in `neighbors` and `umap`)

**Comment by adamgayoso** [comment]
So unfortunately this is an expected behavior. You can see a bit more about this here:

https://github.com/pytorch/pytorch/issues/38219

I think what you can do is move the model to CPU after training with this [method](https://docs.scvi-tools.org/en/stable/api/reference/scvi.model.SCVI.to_device.html#scvi.model.SCVI.to_device) and then get the latent representation/other items on cpu. It should be reproducible on Intel cpus hopefully for the same pytorch version.

**Comment by grst** [comment]
I see, thanks for clarifying!

**Comment by adamgayoso** [comment]
Reopening this so that we don't forget to add this message.
