### ISSUE TITLE
[AnnData setup refactor] Refactor steps involved in setup_anndata using AnnDataRefactor

### ISSUE THREAD

**Issue by watiss** [YosefLab/scvi-tools#1136]
See [this](https://docs.google.com/document/d/18howmTv4eg6dOBIEaJTpUr1DsS2GaaYmZewgy6lB_ME/edit?usp=sharing) doc for details, and [this](https://github.com/YosefLab/scvi-tools/pull/948) PR for a draft implementation

Another issue we want to address is using other keys in addition to the ones we register today (e.g. _scvi_batch, etc.), such as _scvi_donor, etc. This will need to account for setup validation and transfer as well.

**Comment by adamgayoso** [comment]
Model specific params (relative to global setup anndata)

All except protein params:

1. scANVI
2. scVI

All except labels:

1. totalVI

All except labels and protein params:

1. peakVI
2. multivi

Only layer and labels:

1. CondSCVI
2. destvi
3. RNAStereoscope


Others:

1. LinearSCVI (layer and batch key)
2. Autozi (layer, batch, labels)
3. spatialstereoscope (layer, but uses alternate constructor)
4. SOLO (complicated because it uses alternate constructor)

**Comment by adamgayoso** [comment]
Two related issues which maybe we can also address here:

https://github.com/YosefLab/scvi-tools/issues/1044

https://github.com/YosefLab/scvi-tools/issues/945

Regarding the second one, this should already be covered by this issue as it will be up to the developer to include this check.
