### ISSUE TITLE
Workflow for gene selection in scvi-tools

### ISSUE THREAD

**Issue by Munfred** [YosefLab/scvi-tools#781]
Hi, thanks for the scvi-tools release, I really like that everything is now neatly tied together under the `model` class!

I have a question about the expected workflow for performing gene selection. Since we now first prepare the adata with `scvi.data.setup_anndata`, should we be performing gene selection in the adata itself, before calling `scvi.data.setup_anndata`?

For example, in the old API I first filter genes by a minimum number of counts per batch using `gene_dataset.filter_genes_by_count`, then use the `gene_dataset.subsample_genes` method with the   `poisson_zeros` mode to select genes. 

In the new API, should I be doing this selection directly with the adata? I saw that the poisson gene section function is still available under `scvi.data.poisson_gene_selection`, but I did not find the function `filter_genes_by_count`. Is the suggestion that this filtering be done with scanpy?

Below I'm copying a snippet showing how I'd do the gene selection and training with the old API, and how to do it with the new API which I took from the tutorial. The only part I'm not totally sure how the recommended way to do is the gene filtering and gene selection.

Thanks!

### Old API

```python
### Old API
import scvi
adata = anndata.read('my_adata.h5ad')
gene_dataset = scvi.dataset.AnnDatasetFromAnnData(adata, # make gene dataset from adata
                                    ctype_label='cluster_label', # cell type label
                                    batch_label='batch_id' # add batch labels
                                  ) 
vae = scvi.models.VAE('n_input':gene_dataset.nb_genes, 'n_batch':gene_dataset.n_batches ) # specify VAE parameres 

#filter genes with less than 100 counts in at least one batch
gene_dataset.filter_genes_by_count(min_count = 100, per_batch=True)
# select genes using the poisson_zeros
gene_dataset.subsample_genes(3000, batch_correction= True,mode="poisson_zeros")
trainer = scvi.inference.UnsupervisedTrainer(vae, gene_dataset) # create trainer

trainer.train(frequency=1, n_epochs = 100) # train
trainer.history ## access training history

full_posterior = trainer.create_posterior( # create posterior
	trainer.model, 
	gene_dataset, 
	indices=np.arange(len(gene_dataset)))

latent, batch_indices, labels = full_posterior.sequential().get_latent()
```

### New API

```python
### New API

import scvi
adata = anndata.read('my_adata.h5ad')
adata.layers["counts"] = adata.X.copy() # preserve counts

### perform gene selection here, before setup_annata? e.g.
# scvi.data.poisson_gene_selection(adata)
# adata = adata[:,adata.var['highly_variable']]


scvi.data.setup_anndata(adata, layer="counts", batch_label='batch_id') 

### or perform gene selection here, after setup_anndata? 

model = scvi.model.SCVI(adata,  n_hidden=n_hidden, n_latent = n_latent)
model.train(frequency=1, n_epochs = 100)
model.trainer.history # check training history
latent = model.get_latent_representation() # get latent
```

**Comment by adamgayoso** [comment]
Hi @Munfred ,

> Since we now first prepare the adata with scvi.data.setup_anndata, should we be performing gene selection in the adata itself, before calling scvi.data.setup_anndata?

All preprocessing (and gene selection) should occur before the call to `setup_anndata`. In the quick start we put the following warning message as well as the info message from `setup_anndata` to warn against editing an already setup anndata, but perhaps we can make this more clear.

![Screen Shot 2020-09-22 at 10 07 13 AM](https://user-images.githubusercontent.com/10859440/93914426-64e47880-fcbb-11ea-9611-b3d59dfd1311.png)

The idea of `setup_anndata` is that scvi-tools puts a setup dictionary into the anndata itself that is used during the vae creation and is used for data loading into the model. So editing your anndata after `setup_anndata` and before model creation/training will probably lead to errors, and in most cases the model will catch this and give you an informative message back.

> Is the suggestion that this filtering be done with scanpy?

Yes, we removed all superfluous data preprocessing functions and refer to scanpy for these steps. We didn't feel the need to duplicate a bunch of functionality from scanpy. We also suggest the following workflow.

```python
# basic filtering steps not shown
adata.layers["counts"] = adata.X.copy() # preserve counts
sc.pp.normalize_total(adata, target_sum=1e4)
sc.pp.log1p(adata)
adata.raw = adata # freeze the state in `.raw`, so subsetting genes in X will still leave .raw as all genes
# gene selection not shown.
# setup anndata using the layer
```

> I saw that the poisson gene section function is still available under scvi.data.poisson_gene_selection

We kept this function as it uses torch and the GPU, otherwise I would have made a PR with it in scanpy. I think this gene selection is good, and so it the seurat_v3 flavor in scanpy.

**Comment by adamgayoso** [comment]
Note that we found an issue with C order vs F order of the memory in the layer. F order is a lot slower. We have this fixed stage for another alpha release today or tomorrow.

**Comment by Munfred** [comment]
Thanks for the quick response! That answers my questions!

**Comment by adamgayoso** [comment]
fyi, you should update your pip install as we fixed that issue
