### ISSUE TITLE
how to get corrected expression matrix after batch removal

### ISSUE THREAD

**Issue by wangmhan** [YosefLab/scvi-tools#786]
Hi, I am trying out scVI for batch removal. 
The latent space looks really promising. I tried this tutorial (https://www.scvi-tools.org/en/stable/tutorials/basic_tutorial.html).
But for the following analysis, I would like to have corrected expression matrix as well.
To my understand, It seems imputed and normed matrix the same thing as corrected expression matrix after batch removal. Could you please give some suggestions how to extract the corrected expression matrix? Big thanks!

**Comment by adamgayoso** [comment]
Hello, you'll see that the `get_sample_scale` method has a `transform_batch` [option](https://www.scvi-tools.org/en/stable/api/scvi.inference.Posterior.html#scvi.inference.Posterior.get_sample_scale).

You can use this so that the normalized expression is all conditioned on the same batch (one of the batches in your dataset). You can call this function multiple times with different transform batch integers and average the result.

You can then multiply the result by 10,000 to have an output with similar interpretation to Seurat/Scanpy.

**Comment by adamgayoso** [comment]
Please let me know if you have any other questions!

**Comment by wangmhan** [comment]
Thank you, it helps.
I am trying out the method. Will let you know if I have further questions.
