### ISSUE TITLE
Add Solo to scVI tools

### ISSUE THREAD

**Issue by njbernstein** [YosefLab/scvi-tools#922]
Hi all,

We discussed this a while ago, and I finally have a bit of bandwidth.

Goal: Have solo be a model directly within `scvi-tools`

This still cool with you guys?

Best,
Nick

**Comment by njbernstein** [comment]
@adamgayoso You mentioned I should not use the scVI classifier module for `solo`, and instead code up my own vanilla NN. Is that still the recommendation? I see the classifier module seems to be up and running.

**Comment by adamgayoso** [comment]
Hi @njbernstein 

Yes we have a classifier, though haven't really completed adding a `TrainingPlan` class for the classifier. So as of now there's not yet a way to train just a classifier. 

That said, I think to add solo to the codebase it's more about API decisions. 

1. Should solo accept a pre-trained scvi model object as input? (with checks that it was trained on one lane)
2. If solo gets a dataset with multiple batches (lanes), it trains scvi per batch, right?
3. Are solo users tending to be on CPU/GPU? Maybe a sklearn MLP classifier is sufficient, since there's unlikely to be more than 20,000 observations and `n_latent` + 1 features, with the +1 being the library size. A sklearn MLP may be surprisingly fast, as if I recall now, you're re-encoding cells to train the classifier.
4. What needs to be saved and loaded? The scvi model? The classifier? 

How do you envision the workflow?

**Comment by njbernstein** [comment]
1. Yes
2. Yes
3. It seems most use CPUs, but I'm hesitant to switch to sklearn. For scalability, I think GPUs will be necessary as datasets get larger. Also, it's been quite a while since I've used the MLP in sklearn, but I remember not having great luck with it.
4. Not sure what would be necessary, but I think both the scVI model and the classifier would be nice to save. That might be partially/completely a decision for a wrapper script in a separate repo.

I think your description when this first came up makes sense:
```
adata = sc.read...
scvi.data.setup_anndata(adata)
vae = scvi.model.SCVI(adata)
vae.train()
solo = scvi.model.SOLO(vae)
solo.train() # simulates doublets, trains classifier
solo.predict(adata)
```

**Comment by adamgayoso** [comment]
Please checkout the PR.

I think it's easiest for us if the workflow follows the one presented in the docstring examples. The decision to run SCVI/SOLO for multiple batches is something that should be handled by your CLI.

Saving and loading the `SOLO` object works automatically, but only saves the classifier.

We can move this conversation over to the PR.

**Comment by njbernstein** [comment]
This is great! Thank you! I was still working my around understanding the repo structure.
